Implement topologySpreadConstraints
kubemod/kubemod-helm pull request #20
Opened 2023-01-27 10:49 UTC by runningman84

this is useful for ha purpose

2023-09-13 11:43 UTC, runningman84 commented
@vassilvk  would you mind merging this?

2023-09-20 21:13 UTC, vassilvk commented
Hi @runningman84, did you see my comment regarding `DoNotSchedule` for topology key `kubernetes.io/hostname`?

2023-09-21 05:03 UTC, runningman84 commented
No I have not seen any comment. The reason for do not schedule on the same node is because it creates a false sense of security and increases outages . I would rather have a second pod in pending state which would result in karpenter or cluster autoscaler creating another node.

2023-09-25 13:19 UTC, vassilvk commented
Hi @runningman84 - yes, this makes sense.
Please fix the failing lint test by bumping the chart version and we can go ahead with the merge.

2023-09-30 03:47 UTC, vassilvk requested changes

2023-09-30 03:47 UTC, vassilvk commented on helm-chart/kubemod/templates/deployment.yaml
> +        whenUnsatisfiable: DoNotSchedule
Not sure I agree with `DoNotSchedule` for this topology key.
We should be able to deploy multiple instances of KubeMod to the same node in order to provide high availability.

2023-09-30 03:47 UTC, vassilvk commented on helm-chart/kubemod/Chart.yaml
> +version: 0.4.1
Hi @runningman84, please set the version to 0.5.1

2023-09-30 03:52 UTC, vassilvk commented on helm-chart/kubemod/templates/deployment.yaml
> +        whenUnsatisfiable: DoNotSchedule
Resolving this as I agree with @runningman84‘s notion regarding HA and forcing provisioner node spin up through unschedulable pod.

2023-09-30 16:25 UTC, merged